### ISSUE TITLE
Does Secure Boot Need to be Enabled?

### ISSUE THREAD

**Issue by Rrojas93** [eclypsium/BootHole#6]
Does secure boot need to be enabled for this script to detect if you are vulnerable to boot hole? 

Running the PowerShell script yields: 
```
[+] Secure boot is Disabled
[+] No revoked binaries were detected
```

**Comment by HackingThings** [comment]
No, The Secure Boot output is informational only, the check is performed regardless of Secure Boot state.

**Comment by Rrojas93** [comment]
Awesome, Thank you for clarifying!
